### Задание 1
Создайте матрицу таблицы умножения с использованием списков

In [13]:
import pandas as pd
import numpy as np

In [14]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])

In [15]:
umn = np.outer(a,b)

In [16]:
umn

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

### Задание 2
Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число el1), и разность (вещественное число d) и создает матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии. 

In [17]:
def create(n, el1, d):
    return np.diag(np.arange(el1, el1+n*d, d))

In [18]:
create(10,2,3)

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 14,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 17,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 20,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 23,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 26,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 29]])

### Задание 3
Из данных по температуре в Стокгольме выбрать данные относящиеся к октябрю 1970 года и записать их в бинарный и текстовый файлы oct70.bin и oct70.txt. Затем прочитайте их импортировав в тетрадь ноутбука и сравните.

In [20]:
data = np.genfromtxt('stockholm_td_adj.dat')

In [21]:
data[(data[..., 0] == 1970) & (data[...,1] == 10)].tofile('oct70.bin')

In [23]:
np.savetxt('oct70.txt',data[(data[..., 0] == 1970) & (data[...,1] == 10)])

In [25]:
txt = np.genfromtxt('oct70.txt')

In [27]:
bin_ = np.fromfile('oct70.bin')

In [28]:
df_describe = pd.DataFrame(txt)
df_describe.describe()

0     1          2          3          4          5     6
count    31.0  31.0  31.000000  31.000000  31.000000  31.000000  31.0
mean   1970.0  10.0  16.000000   7.154839   6.870968   6.870968   1.0
std       0.0   0.0   9.092121   3.492262   3.512757   3.512757   0.0
min    1970.0  10.0   1.000000   0.800000   0.500000   0.500000   1.0
25%    1970.0  10.0   8.500000   4.200000   3.900000   3.900000   1.0
50%    1970.0  10.0  16.000000   8.100000   7.800000   7.800000   1.0
75%    1970.0  10.0  23.500000  10.000000   9.750000   9.750000   1.0
max    1970.0  10.0  31.000000  12.500000  12.200000  12.200000   1.0

In [29]:
df_describe = pd.DataFrame(bin_)
df_describe.describe()

0
count   217.000000
mean    288.270968
std     688.175037
min       0.500000
25%       3.300000
50%       9.800000
75%      12.200000
max    1970.000000

### Задание 4
Используя срезы извлеките нечетные элементы матрицы А. 

In [30]:
A = np.array([1,2,3,4,5])

In [31]:
A[A % 2 != 0]

array([1, 3, 5])

In [32]:
A[0::2]

array([1, 3, 5])

### Задание 5
Используйте массив из задания 1 (таблицу умножения) извлеките из него при помощи маски все числа кратные 3. 

In [33]:
umn[umn % 3 == 0]

array([ 3,  6,  9,  6, 12, 18,  3,  6,  9, 12, 15, 18, 21, 24, 27, 12, 24,
       36, 15, 30, 45,  6, 12, 18, 24, 30, 36, 42, 48, 54, 21, 42, 63, 24,
       48, 72,  9, 18, 27, 36, 45, 54, 63, 72, 81])

### Задание 7
Разбить массив таблицы умножения из задания 1 на два массива содержащие четные и нечетные значения, а затем собрать его в исходное состояние используя choose()

# скип

### Задание 8
Даны вектора v1(0,1,2,3,4) v2(5,6,7,8,9) найти угол между ними, учитывая что косинус угла между векторами можно найти как отношения их скалярного произведения к их длинам.

In [ ]:
v1 = array([0,1,2,3,4])

In [ ]:
v2 = array([5,6,7,8,9])

In [ ]:
import math

def dotproduct(v1, v2):
    return (v1*v2).sum()

def length(v):
    return math.sqrt(dotproduct(v, v))

def angle(v1, v2):
    return math.acos(dotproduct(v1, v2) / (length(v1) * length(v2)))

In [ ]:
(v1*v1).sum()

30

In [ ]:
(v2*v2).sum()

255

In [ ]:
angle(v1,v2)

0.41613250096978566

### Задача 9
Создайте две матрицы размером (5,5). Одна матрица содержит 5 в шахматном порядке как в задаче домашнего задания, другая имеет треугольную форму содержающую 5 на основной диагонали и в позициях выше ее, а ниже все 0. Посчитайте их детерминант и найдите обратные матрицы. Если для матрицы не у дается найти обратную, видимо этому мешает нулевое значение детерминанта.

In [38]:
first = np.array([[5 if (i+j)%2 else 0 for i in range(5)] for j in range(5)])

In [39]:
second = np.array([[5 if (i>=j) else 0 for i in range(5)] for j in range(5)])

In [40]:
first

array([[0, 5, 0, 5, 0],
       [5, 0, 5, 0, 5],
       [0, 5, 0, 5, 0],
       [5, 0, 5, 0, 5],
       [0, 5, 0, 5, 0]])

In [41]:
second

array([[5, 5, 5, 5, 5],
       [0, 5, 5, 5, 5],
       [0, 0, 5, 5, 5],
       [0, 0, 0, 5, 5],
       [0, 0, 0, 0, 5]])

In [42]:
np.linalg.det(first)

0.0

In [43]:
np.linalg.det(second)

3124.999999999999

In [44]:
np.linalg.inv(second)

array([[ 2.00000000e-01, -2.00000000e-01,  1.11022302e-17,
        -6.16297582e-34,  3.42113883e-50],
       [ 0.00000000e+00,  2.00000000e-01, -2.00000000e-01,
         1.11022302e-17, -6.16297582e-34],
       [ 0.00000000e+00,  0.00000000e+00,  2.00000000e-01,
        -2.00000000e-01,  1.11022302e-17],
       [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
         2.00000000e-01, -2.00000000e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.00000000e-01]])

In [45]:
np.linalg.inv(first)

LinAlgError: Singular matrix